### PR TITLE
Annotate dataset

### PR DESCRIPTION
**Pull request by drugilsberg**

### CODE REVIEW

**Review by jannisborn — COMMENTED** [review]
@drugilsberg  Looks fine. It's a good idea to use `selected_sample.name` as oppose to `[:num_tasks]`.

For the test, we could add one test where the first column(indexes)  is missing and seeing whether the result is the same, what do you think?

**Comment by drugilsberg** [comment]
In principle I agree, but we need to relax the requirement of having the index.
Basically this line should diseappear:
```
kwargs['index_col'] = kwargs.get('index_col', 0)
```
And in case someone provide something with an index column in position zero that we want to discard can provide `index_col=0` to the constructor.
I would honestly prefer this.
@jannisborn What do you think?

**Comment by jannisborn** [comment]
We should definetely relax this assumption, but it would be perfect if the presence of the column could be inferred dynamically. 

This is the usecase we have atm in cytotox, 2 different files, one with index_col=0 but one without.

**Comment by drugilsberg** [comment]
Unfortunately this is not possible, because beforehand is impossible to know/interpret the structure of the csv. This is also the reason why pandas provide the `index_col` option.
IMHO, the best would be to remove the default index assigned to the 0th column and afterwards the user can tell whether such index is present or not.
In this case the only change in a script using this, it is in a single parameter in the `AnnotatedDataset` initialization.

**Comment by jannisborn** [comment]
Not ideal. But yep, then it boils down to having an `index_col` parameter as input, which defaults to None in which case it is assumed that no index is there. If it is provided, it will be passed to `pd.read_csv`.

Hence, the only required change is literally to delete the default of 0 in the constructor.

**Comment by drugilsberg** [comment]
Great will implement the change and add a test case. Then merge and release.

**Review by jannisborn — APPROVED** [review]

**Pull request merged**
