### PR TITLE
Speedup for large datasets & deal invalid SMILES

### LINKED ISSUE #22: Remove invalid SMILES
Atm, the `SMILESDataset` setup fails if there is a single invalid SMILES.

We should do two things:

1. raise a warning whenever an invalid SMILES is encountered. The transforms (like canonicalization) will not apply and the raw SMILES will be tokenized (@jannisborn)
2. Create a script that parses a `.smi` file and removes all invalid SMILES (@drugilsberg).

### PR DESCRIPTION
**Pull request by jannisborn**
1. **`SMILESDataset` can now handle invalid SMILES**. Whenever an invalid SMILES is encountered, the respective SMILES transform (e.g. canonicalization,  removeIsomery, Augmentation) is skipped. We raise a warning that this happens. After the parse is completed, we also show how many molecules were found invalid and we also show if the language transforms (e.g. augmentation) led to adding any new tokens to the smiles language.

2. **Performance speedup**: This affects you @niladell. Everything described in 1) only happens if you specify at least one language_transform, i.e. one of the following is true:
    - `canonical`
    - `augment`
    - `kekulize`
    - `all_bonds_explicit`
    - `all_hs_explicit`
    - `remove_bonddir`
    - `remove_chirality`
In that case the Dataset constructor can take a *very* long time to setup since it has to run *twice* over the entire dataset (which may contain millions or billions of SMILES) and perform all specified transforms (most of them include several `RDKit` calls). But you can avoid running over the entire data in the constructor and get a much faster setup (~2 sec for 1M SMILES on my local CPU). To do this, you have to pass your own `SMILESLanguage` object **and** set any of the above language_transforms to False. The reason is simple. If you don't provide a SMILES language object, there's no way the dataset can create the mapping between SMILES tokens and integers, so it has to run over the data. If you provide one language transform, the SMILES strings are changed prior to tokenization and this may result in new tokens, so as a security operation we have to perform the pass over the data. 
Take home message is: If you want a fast `SMILESDataset`, create your `SMILESLanguage`(or `PolymerLanguage`) object offline for your desired data, save it on your disk and then pass it to the Dataset constructor.

### CODE REVIEW

**Comment by niladell** [comment]
Maybe it'd be interesting to check at this https://github.com/rdkit/rdkit/issues/2708. Some correct compunds in PubChem are not deemed valid by RDkit.

**Comment by jannisborn** [comment]
I actually believe that this behavior is intended. I think these high oxidation state are rather unusual and you can simply set `sanitize=False` if you are sure that your SMILES is valid.

@niladell Do you think it would good to have a global `sanitize` parameter in `SMILESDataset` and `SMILESLanguage` that controls the sanitization of every `Chem.MolFromSmiles` call?

**Comment by niladell** [comment]
@jannisborn I guess that'd do. Smiles get canonicalized regardless of sanitization, right? How much do you think I should trust these databases (ZINC, ChEMBL, etc.) to ignore sanitization on them? Or do you think we should do some automatic checking whenever the SMILES is not valid? E.g. if SMILES is invalid, check if it exists in PubChem (to name a DB), if so set `sanitize=False`.

**Comment by drugilsberg** [comment]
@niladell this option, while nice in principle would kill performance when generating the batches for training. I would suggest to have sanitize as a flag.

**Comment by jannisborn** [comment]
Yep, canonicalization is independent of sanitization as it is controlled in `Chem.MolToSmiles`. Even if you set it to `True`, the SMILES of a compound that cannot be parsed without `sanitize=False` results in SMILES that are again invalid (with `sanitize=True`).
My trust on ZINC is higher than on Chembl, where I definitely found some badly formatted SMILES.

I agree, we should allow the user to set a sanitize parameter. Do you think you could adapt the code? I think affected to pass the parameter down are `SMILESDataset` (plus all dependent classes), and `PolymerDataset`. The actual code change needs to happen in `smiles/transforms.py`

**Comment by niladell** [comment]
Sure, I'll give it a look tomorrow :)

@drugilsberg fair point, flag it is then.

**Review by jannisborn — COMMENTED** [review]
@niladell I'm tagging you since this pull request affects you and the speed of the `PolymerDataset` class. It's more controllable now. Let me know if you have questions

**Pull request merged**
