### PR TITLE
Protein Language Modeling

### PR DESCRIPTION
**Pull request by jannisborn**
I created a few tools for protein language modeling. Specifically, we now have 3 new classes which build on top of each other:

1. `ProteinLanguage`
-  This is part of a new submodule `pytoda/proteins`. Import as: `from pytoda.proteins import ProteinLanguage`. It is heavily inspired by the `SMILESLanguage` class and deals with all routines to convert amino acid text sequences back and forth to numerical representations (`protein_language.sequence_to_token_indexes` and `protein_language.token_indexes_to_sequence`)
- `ProteinLanguage` can deal with the two very common text notations for AA sequences, namely `iupac` and `unirep`. Default is `iupac`. Both these dictionary are taken from [`TAPE`](https://github.com/songlab-cal/tape/blob/master/tape/tokenizers.py). @mfilipav: Am I missing common notations? If so, please point me to them so that I can add them or add them by yourself.

2. `ProteinSequenceDataset`
- This dataset can be imported as: `from pytoda.datasets import ProteinSequenceDataset`. It is intended to facilitate unsupervised or self-supervised learning of protein sequences. 
- You can call it with a list of tab separated (!) `.smi` or `.csv` files of protein sequences and it will create a `ProteinLanguage` object (unless you pass one) to maintain the string-to-tensor conversion. 
- If you want, you can tell it to make use of data transforms, e.g. you can perform a data augmentation by reverting the sequences in 50% of the cases (`augment_by_revert=True`, I'm not sure how valid this is or whether there are more ways of augmentation @C-nit ?). Other (`bool`) options are `add_start_and_stop_token`, `padding` and `randomize` (which destroys the structure and generates a random protein with the same AA frequencies as the original one).

3. `ProteinProteinInteractionDataset` 
- This dataset is build on top of `ProteinSequenceDataset` and can be imported by: `from pytoda.datasets import ProteinProteinInteractionDataset`. This dataset can be used for all downstream tasks of property prediction from an *arbitrary amount of protein sequences*.
- The class receives an Iterable of filepaths, one for each protein entity. In addition you have to give an iterable of the same length with the entity names, e.g. '["TCellReceptor", "Peptide"]' if your task is to predict whether a given peptide-TCR binds. But the code is generic, you could use it to predict properties of a `n-tuple` of protein sequences. The third positional argument is `labels_filepath` which points to a `.csv` with the properties/labels. Again this is generic and can be multi-task, so by default all columns in this file that are not entity names are treated as labels.
- If you want to predict a single property of your `labels_filepath`, you can determine the column by specifying `annotations_column_names` (either as `str` or  as `int`).
- Finally, you can control all parameters of `ProteinSequenceDataset` (like `padding`, `augment_by_reverting` and `randomize`) either globally with a bool, or individually for each protein entity.

I also added unittests for all 3 classes.

### CODE REVIEW

**Comment by drugilsberg** [comment]
Looks very good. I would just add the possibility to handle FASTA files, that are the standard for proteins. I created a PYPI package that can be installed called upfp some time ago. Here the repo: https://github.com/drugilsberg/uniprot_fasta_parser.
It should straightforward to call it based on the extension.

**Comment by jannisborn** [comment]
@drugilsberg I improved the interface to understand `.fasta` and `.fasta.gz` files. This option exists for all 3 classes. I had to create a `_FastaEagerDataset`, similar to the `_SmiEagerDataset`.

**Comment by jannisborn** [comment]
@annaweber209 also for you, specifically check the `ProteinProteinInteractionDataset`.

**Comment by drugilsberg** [comment]
> o understand `.fasta` and `.fasta.gz` files. This option exists for all 3 classes. I had to create

great work @jannisborn, looks good to me.

**Review by drugilsberg — APPROVED** [review]

**Review by drugilsberg — COMMENTED** [review]
Add `tokenizer_fn` to `ProteinLanguage` constructor.

**Comment by jannisborn** [comment]
@mfilipav @C-nit 
I'm done with this now. If you don't have further comments, please approve the pull request.

As for the masking, @mfilipav, I would suggest that we wait after this is merged and then branch out again. Just notify me if you want to sit down and discuss the next steps there.

**Review by mfilipav — CHANGES_REQUESTED** [review]
Looks good to me, and in terms of notations, thanks for expanding iupac_vocab and unirep_vocab (as seen in TAPE) with <start>, <stop>  and <unk> tokens.

L100 and L104 are duplicated (same `<SEP>` token) in https://github.com/PaccMann/paccmann_datasets/blob/protein_language/pytoda/proteins/processing.py

**Pull request merged**
