### PR TITLE
Gh actions

### PR DESCRIPTION
**Pull request by C-nit**

### CODE REVIEW

**Comment by jannisborn** [comment]
Since this PR makes the `.travis.yml`, the `.travis/` folder and also the `.dockerignore` obsolete, we could remove these files in this PR, no?

**Comment by jannisborn** [comment]
Not super sure, I can review this, lacking expertise with github actions. A few points:
- I think we should fix the linter/black checks that fail OR remove them from the checklist. Some of those checks seem quite harsh to me, but it might be a good habit to start sticking to these tests.
- more of a q: Why did we depend on docker and the rdkit image in travis but not anymore right now? It seems a bit black magic to me that we now can run tests on macOS, ubuntu and Windows without any docker/containerization

**Comment by C-nit** [comment]
the points you raise are exactly why it's good to have your eyes on this.

I agree on fixing the checks, I was thinking to do it in a separate PR dedicated to that (also trying to fix windows builds that on a glance seem only to break due to line endings). What do you think?

Only the build and security are required to succeed to allow merging into master. But I agree that in the sum of them they become quite hard to get a green tick on a commit.

Travis also allows different operating systems actually, it's just that it was harder to set up conda in each case. We just never did it for travis. So the real difference is that github actions makes it much easier to set up. here it was not special effort to get it.

**Review by jannisborn — APPROVED** [review]

**Comment by jannisborn** [comment]
Thanks for the explanation about conda.
My opinion on the first bit is that we should **never** merge PRs that have unsuccessful checks. I would rather fix the checks in this PR. What's the point of a check if we just ignore it?

**Comment by C-nit** [comment]
wow great work fixing all the checks! Pristine

**Pull request merged**
